### ISSUE TITLE
Alexander Avilez

### ISSUE THREAD

**Issue by AlexanderAvilez** [pgalvez9/TSM#12]
¿Cuál es la función del Product owner?

**Comment by arturoOG** [comment]
El Product owner (PO) actúa como el punto de contacto entre el equipo de desarrolladores y los stakeholders. Conoce los requerimientos que esperan los stakeholders , los filtra/agrupa y los transmite al equipo de desarrollo.  Al mismo tiempo, cualquier duda que tenga el equipo de desarrolladores sobre el proyecto pasa por el PO. Nunca se tiene contacto directo entre los stakeholders y el equipo de desarrolladores.

**Comment by pgalvez9** [comment]
Genial @arturoOG, @AlexanderAvilez  estas satisfecho con la respuesta?

**Comment by AlexanderAvilez** [comment]
Sí, muy bien contestada
