### ISSUE TITLE
Arturo Obregón

### ISSUE THREAD

**Issue by arturoOG** [pgalvez9/TSM#2]
Prueba issue

**Comment by arturoOG** [comment]
¿En qué consiste en Product Backlog?

**Comment by pgalvez9** [comment]
@AlexanderAvilez  puedes contestar la pregunta de Arturo?

**Comment by AlexanderAvilez** [comment]
Es una lista de los requerimientos que debe cumplir el proyecto y es manejada por el Product Owner
