### ISSUE TITLE
Rogelio Mendoza

### ISSUE THREAD

**Issue by rog3113** [pgalvez9/TSM#3]
⚽

**Comment by rog3113** [comment]
¿Qué es el product backlog?

**Comment by pgalvez9** [comment]
@samrs  puedes contestar la pregunta de Rogelio?

**Comment by samrs** [comment]
Es la lista de cosas por hacer, lo que le falta al proyecto. El product owner se encarga de establecer la lista.

**Comment by pgalvez9** [comment]
Gracias!
