### ISSUE TITLE
Diego

### ISSUE THREAD

**Issue by Diego912** [pgalvez9/TSM#8]
# Hola
## Mi primer issue

**Comment by pgalvez9** [comment]
@Diego912  genial que jugaras con el Mardkdown!! Puedes generar una pregunta de scrum y asignarla a alguno de tus compañeros?

**Comment by Diego912** [comment]
¿Cuánto tiempo debe durar un daily scrum?

**Comment by pgalvez9** [comment]
@arturoOG  puedes contestar la pregunta de @Diego912 ?

**Comment by arturoOG** [comment]
Un daily scrum debe durar máximo 15 minutos, y se lleva a cabo todos los días hasta que se termine un sprint.
