### ISSUE TITLE
Sebastian Martínez

### ISSUE THREAD

**Issue by SM-gh** [pgalvez9/TSM#9]
Cuales son las tareas o función del SCRUM Master?

**Comment by pgalvez9** [comment]
@SM-gh  puedes asignar el issue a alguno de tus compañeros?
Recuerda hacer una pregunta sobre SCRUM

**Comment by Orlando71297** [comment]
Es el que agiliza y gestiona la aplicación la metodología, así mismo ayuda al product owner y al equipo de trabajo en la comunicación y adopción la metodología.
